spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/application
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: vlad179711v2@gmail.com
    password: imue eqzc ixyg rlxf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
