spring:
  application.name: spring
  datasource:
    url: jdbc:postgresql://localhost:5432/application
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          openid:
            client-id: 89a015d24a66b01a77fe30059820593e177c43b32c9c3c4ea711eb5610639347
            client-secret: 1c1d2b50e647288824223edfbf0fafd1a003c063c5c7191b8b7ac42fb7ca714f
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: http://repair.laop.ulstu.ru/wp-admin/admin-ajax.php?action=openid-connect-authorize
            client-name: openid
        provider:
          openid:
            authorization-uri: https://lk.ulstu.ru/?q=oidc/auth
            token-uri: https://lk.ulstu.ru/?q=oidc/token
            user-info-uri: https://lk.ulstu.ru/?q=oidc/userinfo
            jwk-set-uri: https://lk.ulstu.ru/?q=oidc/jwks
            user-name-attribute: sub

  web:
    resources:
      static-locations: file:src/main/source/images/

  mail:
    host: smtp.gmail.com
    port: 587
    username: vlad179711v2@gmail.com
    password: imue eqzc ixyg rlxf
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    server-url: http://repair.laop.ulstu.ru

openid:
  client-id: 89a015d24a66b01a77fe30059820593e177c43b32c9c3c4ea711eb5610639347
  client-secret: 1c1d2b50e647288824223edfbf0fafd1a003c063c5c7191b8b7ac42fb7ca714f
  scope: openid
  login-endpoint: https://lk.ulstu.ru/?q=oidc/auth
  token-endpoint: https://lk.ulstu.ru/?q=oidc/token
  end-session-url: https://lk.ulstu.ru/?q=auth/logout
  redirect-uri: http://repair.laop.ulstu.ru/wp-admin/admin-ajax.php?action=openid-connect-authorize


